I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ('gui/rotate.png') at 0x0000000005f8c460>:
  File "game/tetris3.rpy", line 685, in script
    call screen draw_tetris
ScriptError: could not find label 'contD6_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Yusri Zafri\Desktop\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Yusri Zafri\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "C:\Users\Yusri Zafri\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "C:\Users\Yusri Zafri\Desktop\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/tetris3.rpy", line 685, in script
    call screen draw_tetris
  File "C:\Users\Yusri Zafri\Desktop\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'contD6_2'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
 Version 1.0
Wed Apr 12 14:04:53 2023
